//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/UIInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIInputActions"",
    ""maps"": [
        {
            ""name"": ""SettingUI"",
            ""id"": ""93e67c19-246e-472c-814e-9627ded8b999"",
            ""actions"": [
                {
                    ""name"": ""MainSelectUp"",
                    ""type"": ""Button"",
                    ""id"": ""87780b6d-e72e-4c6f-bb94-9f11ec9592ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MainSelectDown"",
                    ""type"": ""Button"",
                    ""id"": ""1d391eec-22ef-4c8e-a843-74dea8e3ddcc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pouse"",
                    ""type"": ""Button"",
                    ""id"": ""87aa2d3c-1c0e-4ae0-9ffc-2cb3abf8727b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SettingPanel1"",
                    ""type"": ""Button"",
                    ""id"": ""5fec8a7a-62f2-48e0-aab5-6659849e98a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Settingpanel1Up"",
                    ""type"": ""Button"",
                    ""id"": ""7ec55b44-4469-4330-b6f8-36fa5a7678a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Settingpanel1Down"",
                    ""type"": ""Button"",
                    ""id"": ""d6450723-feed-4926-9b4b-3316ae011d71"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SettingPanel2"",
                    ""type"": ""Button"",
                    ""id"": ""17e65689-6afd-475c-94f3-2364697efdc5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Settingpanel2Up"",
                    ""type"": ""Button"",
                    ""id"": ""ad34c293-5b6c-45ea-906d-5af188e8e1f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Settingpanel2Down"",
                    ""type"": ""Button"",
                    ""id"": ""220bf834-4963-4aaf-bdcf-b9b3e289fe20"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f5bbd5e9-e40b-4b1c-b0d6-794bf20dafa4"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40dff9f6-2fb9-4709-ae6b-d1bd0742f3dd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SettingPanel1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a411bd4-c095-4b85-bc54-72ff37f96284"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SettingPanel2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b493f2c2-8aab-4ba9-a5dd-845585131300"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainSelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d03996be-8be4-4a16-ac1c-8b7ce5865f3b"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainSelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc665770-d295-4e50-82bd-2e736ddab796"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Settingpanel2Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""188eeabd-ed74-4ce5-838f-8627d4ca5599"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Settingpanel2Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d333c48-5e8b-4aad-9aaf-d01358044722"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Settingpanel1Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b130812b-7282-4895-98b5-02dac64bc04b"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Settingpanel1Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SettingUI
        m_SettingUI = asset.FindActionMap("SettingUI", throwIfNotFound: true);
        m_SettingUI_MainSelectUp = m_SettingUI.FindAction("MainSelectUp", throwIfNotFound: true);
        m_SettingUI_MainSelectDown = m_SettingUI.FindAction("MainSelectDown", throwIfNotFound: true);
        m_SettingUI_Pouse = m_SettingUI.FindAction("Pouse", throwIfNotFound: true);
        m_SettingUI_SettingPanel1 = m_SettingUI.FindAction("SettingPanel1", throwIfNotFound: true);
        m_SettingUI_Settingpanel1Up = m_SettingUI.FindAction("Settingpanel1Up", throwIfNotFound: true);
        m_SettingUI_Settingpanel1Down = m_SettingUI.FindAction("Settingpanel1Down", throwIfNotFound: true);
        m_SettingUI_SettingPanel2 = m_SettingUI.FindAction("SettingPanel2", throwIfNotFound: true);
        m_SettingUI_Settingpanel2Up = m_SettingUI.FindAction("Settingpanel2Up", throwIfNotFound: true);
        m_SettingUI_Settingpanel2Down = m_SettingUI.FindAction("Settingpanel2Down", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SettingUI
    private readonly InputActionMap m_SettingUI;
    private List<ISettingUIActions> m_SettingUIActionsCallbackInterfaces = new List<ISettingUIActions>();
    private readonly InputAction m_SettingUI_MainSelectUp;
    private readonly InputAction m_SettingUI_MainSelectDown;
    private readonly InputAction m_SettingUI_Pouse;
    private readonly InputAction m_SettingUI_SettingPanel1;
    private readonly InputAction m_SettingUI_Settingpanel1Up;
    private readonly InputAction m_SettingUI_Settingpanel1Down;
    private readonly InputAction m_SettingUI_SettingPanel2;
    private readonly InputAction m_SettingUI_Settingpanel2Up;
    private readonly InputAction m_SettingUI_Settingpanel2Down;
    public struct SettingUIActions
    {
        private @UIInputActions m_Wrapper;
        public SettingUIActions(@UIInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MainSelectUp => m_Wrapper.m_SettingUI_MainSelectUp;
        public InputAction @MainSelectDown => m_Wrapper.m_SettingUI_MainSelectDown;
        public InputAction @Pouse => m_Wrapper.m_SettingUI_Pouse;
        public InputAction @SettingPanel1 => m_Wrapper.m_SettingUI_SettingPanel1;
        public InputAction @Settingpanel1Up => m_Wrapper.m_SettingUI_Settingpanel1Up;
        public InputAction @Settingpanel1Down => m_Wrapper.m_SettingUI_Settingpanel1Down;
        public InputAction @SettingPanel2 => m_Wrapper.m_SettingUI_SettingPanel2;
        public InputAction @Settingpanel2Up => m_Wrapper.m_SettingUI_Settingpanel2Up;
        public InputAction @Settingpanel2Down => m_Wrapper.m_SettingUI_Settingpanel2Down;
        public InputActionMap Get() { return m_Wrapper.m_SettingUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SettingUIActions set) { return set.Get(); }
        public void AddCallbacks(ISettingUIActions instance)
        {
            if (instance == null || m_Wrapper.m_SettingUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SettingUIActionsCallbackInterfaces.Add(instance);
            @MainSelectUp.started += instance.OnMainSelectUp;
            @MainSelectUp.performed += instance.OnMainSelectUp;
            @MainSelectUp.canceled += instance.OnMainSelectUp;
            @MainSelectDown.started += instance.OnMainSelectDown;
            @MainSelectDown.performed += instance.OnMainSelectDown;
            @MainSelectDown.canceled += instance.OnMainSelectDown;
            @Pouse.started += instance.OnPouse;
            @Pouse.performed += instance.OnPouse;
            @Pouse.canceled += instance.OnPouse;
            @SettingPanel1.started += instance.OnSettingPanel1;
            @SettingPanel1.performed += instance.OnSettingPanel1;
            @SettingPanel1.canceled += instance.OnSettingPanel1;
            @Settingpanel1Up.started += instance.OnSettingpanel1Up;
            @Settingpanel1Up.performed += instance.OnSettingpanel1Up;
            @Settingpanel1Up.canceled += instance.OnSettingpanel1Up;
            @Settingpanel1Down.started += instance.OnSettingpanel1Down;
            @Settingpanel1Down.performed += instance.OnSettingpanel1Down;
            @Settingpanel1Down.canceled += instance.OnSettingpanel1Down;
            @SettingPanel2.started += instance.OnSettingPanel2;
            @SettingPanel2.performed += instance.OnSettingPanel2;
            @SettingPanel2.canceled += instance.OnSettingPanel2;
            @Settingpanel2Up.started += instance.OnSettingpanel2Up;
            @Settingpanel2Up.performed += instance.OnSettingpanel2Up;
            @Settingpanel2Up.canceled += instance.OnSettingpanel2Up;
            @Settingpanel2Down.started += instance.OnSettingpanel2Down;
            @Settingpanel2Down.performed += instance.OnSettingpanel2Down;
            @Settingpanel2Down.canceled += instance.OnSettingpanel2Down;
        }

        private void UnregisterCallbacks(ISettingUIActions instance)
        {
            @MainSelectUp.started -= instance.OnMainSelectUp;
            @MainSelectUp.performed -= instance.OnMainSelectUp;
            @MainSelectUp.canceled -= instance.OnMainSelectUp;
            @MainSelectDown.started -= instance.OnMainSelectDown;
            @MainSelectDown.performed -= instance.OnMainSelectDown;
            @MainSelectDown.canceled -= instance.OnMainSelectDown;
            @Pouse.started -= instance.OnPouse;
            @Pouse.performed -= instance.OnPouse;
            @Pouse.canceled -= instance.OnPouse;
            @SettingPanel1.started -= instance.OnSettingPanel1;
            @SettingPanel1.performed -= instance.OnSettingPanel1;
            @SettingPanel1.canceled -= instance.OnSettingPanel1;
            @Settingpanel1Up.started -= instance.OnSettingpanel1Up;
            @Settingpanel1Up.performed -= instance.OnSettingpanel1Up;
            @Settingpanel1Up.canceled -= instance.OnSettingpanel1Up;
            @Settingpanel1Down.started -= instance.OnSettingpanel1Down;
            @Settingpanel1Down.performed -= instance.OnSettingpanel1Down;
            @Settingpanel1Down.canceled -= instance.OnSettingpanel1Down;
            @SettingPanel2.started -= instance.OnSettingPanel2;
            @SettingPanel2.performed -= instance.OnSettingPanel2;
            @SettingPanel2.canceled -= instance.OnSettingPanel2;
            @Settingpanel2Up.started -= instance.OnSettingpanel2Up;
            @Settingpanel2Up.performed -= instance.OnSettingpanel2Up;
            @Settingpanel2Up.canceled -= instance.OnSettingpanel2Up;
            @Settingpanel2Down.started -= instance.OnSettingpanel2Down;
            @Settingpanel2Down.performed -= instance.OnSettingpanel2Down;
            @Settingpanel2Down.canceled -= instance.OnSettingpanel2Down;
        }

        public void RemoveCallbacks(ISettingUIActions instance)
        {
            if (m_Wrapper.m_SettingUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISettingUIActions instance)
        {
            foreach (var item in m_Wrapper.m_SettingUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SettingUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SettingUIActions @SettingUI => new SettingUIActions(this);
    public interface ISettingUIActions
    {
        void OnMainSelectUp(InputAction.CallbackContext context);
        void OnMainSelectDown(InputAction.CallbackContext context);
        void OnPouse(InputAction.CallbackContext context);
        void OnSettingPanel1(InputAction.CallbackContext context);
        void OnSettingpanel1Up(InputAction.CallbackContext context);
        void OnSettingpanel1Down(InputAction.CallbackContext context);
        void OnSettingPanel2(InputAction.CallbackContext context);
        void OnSettingpanel2Up(InputAction.CallbackContext context);
        void OnSettingpanel2Down(InputAction.CallbackContext context);
    }
}
