//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/UIInput/UIInputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIInputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIInputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIInputSystem"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""a0364cd6-8874-4a45-ad2d-f8051e149cad"",
            ""actions"": [
                {
                    ""name"": ""SelectMenu"",
                    ""type"": ""Value"",
                    ""id"": ""5005c4af-86e7-4a10-aac0-b20437209203"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OpenSetting"",
                    ""type"": ""Button"",
                    ""id"": ""b77b1091-1f37-4ef7-885b-11042a30bc72"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Return"",
                    ""type"": ""Button"",
                    ""id"": ""083b2595-5d3e-4869-afb0-fa89226654b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Decision"",
                    ""type"": ""Button"",
                    ""id"": ""c6b92432-0adb-4808-b82c-8a11bdf7e7e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""26e8eb82-cb25-47b5-ae3a-6269999e1de0"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a9fcafe-b21d-48e9-9aae-9a7c0100d860"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSetting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""805e79cc-159b-41b1-924f-70948e039b5e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73291e0d-ad8f-4dc8-8871-8c02c0e9d664"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Decision"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": []
        }
    ]
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_SelectMenu = m_UI.FindAction("SelectMenu", throwIfNotFound: true);
        m_UI_OpenSetting = m_UI.FindAction("OpenSetting", throwIfNotFound: true);
        m_UI_Return = m_UI.FindAction("Return", throwIfNotFound: true);
        m_UI_Decision = m_UI.FindAction("Decision", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_SelectMenu;
    private readonly InputAction m_UI_OpenSetting;
    private readonly InputAction m_UI_Return;
    private readonly InputAction m_UI_Decision;
    public struct UIActions
    {
        private @UIInputSystem m_Wrapper;
        public UIActions(@UIInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectMenu => m_Wrapper.m_UI_SelectMenu;
        public InputAction @OpenSetting => m_Wrapper.m_UI_OpenSetting;
        public InputAction @Return => m_Wrapper.m_UI_Return;
        public InputAction @Decision => m_Wrapper.m_UI_Decision;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @SelectMenu.started += instance.OnSelectMenu;
            @SelectMenu.performed += instance.OnSelectMenu;
            @SelectMenu.canceled += instance.OnSelectMenu;
            @OpenSetting.started += instance.OnOpenSetting;
            @OpenSetting.performed += instance.OnOpenSetting;
            @OpenSetting.canceled += instance.OnOpenSetting;
            @Return.started += instance.OnReturn;
            @Return.performed += instance.OnReturn;
            @Return.canceled += instance.OnReturn;
            @Decision.started += instance.OnDecision;
            @Decision.performed += instance.OnDecision;
            @Decision.canceled += instance.OnDecision;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @SelectMenu.started -= instance.OnSelectMenu;
            @SelectMenu.performed -= instance.OnSelectMenu;
            @SelectMenu.canceled -= instance.OnSelectMenu;
            @OpenSetting.started -= instance.OnOpenSetting;
            @OpenSetting.performed -= instance.OnOpenSetting;
            @OpenSetting.canceled -= instance.OnOpenSetting;
            @Return.started -= instance.OnReturn;
            @Return.performed -= instance.OnReturn;
            @Return.canceled -= instance.OnReturn;
            @Decision.started -= instance.OnDecision;
            @Decision.performed -= instance.OnDecision;
            @Decision.canceled -= instance.OnDecision;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface IUIActions
    {
        void OnSelectMenu(InputAction.CallbackContext context);
        void OnOpenSetting(InputAction.CallbackContext context);
        void OnReturn(InputAction.CallbackContext context);
        void OnDecision(InputAction.CallbackContext context);
    }
}
